name: rz_utils
description: A CLI tool for automating Flutter app setup and file generation made by reza.
version: 1.0.0

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  args: ^2.3.0
  path: ^1.8.0
  process_run: ^0.12.0

executables:
  rz_utils: bin/rz_utils.dart

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
