name: rz_utils
description: A CLI tool for automating Flutter app setup and file generation made by reza.
version: 1.0.1
repository: https://github.com/achreza/rz-flutter-cli
homepage: https://github.com/achreza/rz-flutter-cli

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  args: ^2.3.0
  path: ^1.8.0
  process_run: ^0.12.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
